import Footer from "@/components/CustomElements/Footer/Footer";

import NavigationBar from "@/components/CustomElements/NavBar/NavigationBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { RootLayoutPropsType } from "@/lib/alltypes";
import { allFontVariables } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: RootLayoutPropsType) => {
	return (
		<html
			className={allFontVariables}
			lang="en"
			suppressHydrationWarning>
			<body>
				<ThemeProvider
					attribute={"class"}
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange>
					<header className="container mx-auto px-3 py-4">
						<NavigationBar />
					</header>
					<main className="container px-9 mx-auto">{children}</main>
					<footer className="py-4">
						<Footer />
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
};

export default RootLayout;
