import Footer from "@/components/CustomElements/Footer/Footer";

import NavigationBar from "@/components/CustomElements/NavBar/NavigationBar";
import { ThemeProvider } from "@/components/ThemeProvider";
import { RootLayoutPropsType } from "@/lib/alltypes";
import { allFontVariables } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: RootLayoutPropsType) => {
	return (
		<html
			className={allFontVariables}
			lang="en"
			suppressHydrationWarning>
			<body className="flex min-h-screen flex-col">
				<ThemeProvider
					attribute={"class"}
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange>
					<header className="container mx-auto px-3 py-4 border-b">
						<NavigationBar />
					</header>
					<main className="container mx-auto flex-1 px-9 py-4">
						{children}
					</main>
					<footer className="py-4 pt-2 mt-6 bg-foreground/5">
						<Footer />
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
};

export default RootLayout;
